### ISSUE TITLE
org.jsmpp.extra.NegativeResponseException: Negative response 0000000a found

### ISSUE THREAD

**Issue by vatsalnarry2** [opentelecoms-org/jsmpp#129]
Hi 
i am getting below excpetion while calling submitshortMessage.Can anyone tell what is reason of this error..

 org.jsmpp.extra.NegativeResponseException: Negative response 0000000b found

**Comment by vatsalnarry2** [comment]
org.jsmpp.extra.NegativeResponseException: Negative response 0000000b found

**Comment by pmoerenhout** [comment]
The negative response is received from the SMSC:
0x0000000A ESME_RINVSRCADR Invalid Source Address.
Source address of message is considered invalid. Usually this is because the field is either too long or contains invalid characters.

In your submit_sm request, you specify your source address/ton/npi. Apparently your SMSC restricts your source address. Normally this is to prevent spam message, which could contain any source address. Please contact the SMSC operator on what source address(es) you are allowed to use on your account.

**Comment by vatsalnarry2** [comment]
i resolved issue MSISDN was sent for Destination address
