### ISSUE TITLE
Exception when receive long message

### ISSUE THREAD

**Issue by chuyennm** [opentelecoms-org/jsmpp#50]
Hello Sir,

I have using your lib, when I receive the long message it's throw Exception like:

Exception in thread "pool-2-thread-3" java.lang.ArrayIndexOutOfBoundsException
	at java.lang.System.arraycopy(Native Method)
	at org.jsmpp.util.SequentialBytesReader.readBytes(SequentialBytesReader.java:80)
	at org.jsmpp.util.DefaultDecomposer.readOptionalParameters(DefaultDecomposer.java:625)
	at org.jsmpp.util.DefaultDecomposer.deliverSm(DefaultDecomposer.java:368)
	at org.jsmpp.session.state.SMPPSessionBoundRX.processDeliverSm0(SMPPSessionBoundRX.java:108)
	at org.jsmpp.session.state.SMPPSessionBoundTRX.processDeliverSm(SMPPSessionBoundTRX.java:42)
	at org.jsmpp.session.PDUProcessTask.run(PDUProcessTask.java:91)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

How I resolved it?

Thanks,

**Comment by pmoerenhout** [comment]
Hi Chuuyen,

Do you have the binary message which is received ?
Or can you explain what kind of message it is ?

Regards, Pim

**Comment by chuyennm** [comment]
I have used SMPPSim to test it, 

The message is: "Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,Hello from SMPPSim,"

![image](https://cloud.githubusercontent.com/assets/767746/16705447/4b137acc-45b4-11e6-8d3a-a0155c5f3f3e.png)

it's error from core received the long message.

Cheers,

**Comment by pmoerenhout** [comment]
Hi Chuygen,

I used the SMPP Sim. I see that when the message is 254 chars, all is OK.
When the message is 255, the simulator uses 255 as length, which is illegal in SMPP 3.4. In SMPP 5.0 its legal.
jSMPP then correctly displays (for SMPP 3.4):
Octet String value 'ABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDEFGHIJABCDE' length must be less than or equal to 254. Actual length is 255

When more then 255 characters are send, if goes wrong.
For example, when 256 characters are send, the short_message length is set to 0x00 by the SMPPSim software.
Then jSMPP cannot decode correctly, because the PDU is not following the SMPP specification.

I will add some extra checking on the message length for SMPP 3.4.
But the biggest problem is within SMPPSim.
Longer messages needs to be put into a TLV message_payload, not in short_message....

Form the spec: Applications which need to send messages longer than 255 octets should use the message_payload TLV. In this case the sm_length field should be set to zero


Regards, Pim

**Comment by chuyennm** [comment]
Thanks Sir, im properly understood that.
