### ISSUE TITLE
How to setup the project in eclipse ?

### ISSUE THREAD

**Issue by ILANKUMARAN11** [opentelecoms-org/jsmpp#66]
Kindly provide me the folder structure and where the shell script had to placed while in execute in eclipse.

**Comment by pmoerenhout** [comment]
Could you tell what you try to do. Are you using jSMPP in your project, or do you want to buidl jSMPP from the sources ? If you want to use jSMPP, I would use Maven, to include the jSMPP artifact.

**Comment by ILANKUMARAN11** [comment]
So good to see ur reply.. 
Yes I am using it in my project and I am from INDIA. Hope ur project will support my service provider(AIRTEL) in my country to send SMS.. I didn't use maven since I have copied ur JSMPP code also to my project and manually downloaded sl4jlog and Apache log JAR for JSMPP code required..

**Comment by ILANKUMARAN11** [comment]
So good to see ur reply.. 
Yes I am using it in my project and I am from INDIA. Hope ur project will support my service provider(AIRTEL) in my country to send SMS.. I didn't use maven since I have copied ur JSMPP code also to my project and manually downloaded sl4jlog and Apache log JAR for JSMPP code required..

**Comment by ILANKUMARAN11** [comment]
Kindly find the screenshot of my project structure
![capture](https://cloud.githubusercontent.com/assets/28765854/26572343/3cb899ca-4537-11e7-8a6c-f1a64f8ff04a.PNG)

**Comment by ILANKUMARAN11** [comment]
If U want I can share my Project structure how I did in my Eclipse...

**Comment by pmoerenhout** [comment]
I did see that you use the sources of the jSMPP in your project. I would expect that you use the library (the jar) and then customize some of the examples in your source tree.
Instead of using libraries files in your project, you can use Maven to references and resolve all dependencies. As the jSMPP library is in the Maven Central repository, you only have to reference it,  same as the log4j and slf4j in your project. Your can send me the project, I can modify it to setup a basic SMPP sender...
